### ISSUE TITLE
Fabricskyblock not working on vulkan

### ISSUE THREAD

**Issue by TomXD1234** [AMereBagatelle/fabricskyboxes#104]
When I installed fabricskyblocks for amazing sky and in my pack have custom sky but still it not working with vulkan so what I do

**Comment by AMereBagatelle** [comment]
Minecraft is built on OpenGL, not Vulkan.  FabricSkyboxes is the same.  If you have a mod installed forcing the client to use Vulkan which causes issues, the solution here is to stop using that mod or to reach out to their developers to find out what can be done.  Closing unless more information is provided (reproduction steps, location of incompatibility, etc).

**Comment by TomXD1234** [comment]
> causes

I have find a fork of skybox name FabricSkyBoxes Interop and it work with your mod and it works fine after installing this fork
