### ISSUE TITLE
[multi-texture] Animation bugs

### ISSUE THREAD

**Issue by UsernameGeri** [AMereBagatelle/fabricskyboxes#106]
I found 2 bugs within the `multi-texture` skybox type.

1) If you add multiple [animation objects](https://github.com/AMereBagatelle/fabricskyboxes/blob/1.20.x/dev/docs/schema-v2.md#animation-object) with different textures, the texture used for the first animation will be used for all animations, overriding all other ones.

2) `frameDuration` doesn't work. Only the `duration` parameter can be used to specify the animation speed.

Edit: Here's an example pack. [multi_texture.zip](https://github.com/AMereBagatelle/fabricskyboxes/files/14966947/multi_texture.zip)
It has 8 different lightning animations with different timings and textures (see configs), however you'll see the same texture flashing all at the same time.

**Comment by FlashyReese** [comment]
Fixed in https://github.com/AMereBagatelle/fabricskyboxes/commit/9a271a90efe2d274796188e3ec7ce1e78d91d405
