### ISSUE TITLE
Gradle Out of Date

### ISSUE THREAD

**Issue by lowercasebtw** [AMereBagatelle/fabricskyboxes#107]
I wanted to update this to 24w13a/etc for personal use instead of waiting for 1.20.5, but I get this error
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

**Comment by AMereBagatelle** [comment]
Gradle's latest release is v8.7 (according to [Gradle's Releases Page](https://gradle.org/releases/)), meaning that incompatibility with Gradle 9.0 logically cannot be the error.  I would suggest coming to the [Discord](https://discord.gg/quvzkaV) where we can help to debug the real error.

**Comment by lowercasebtw** [comment]
I joined the discord, im in the fabricksyboxes channel
