### ISSUE TITLE
Bugfix release for 1.20.1

### ISSUE THREAD

**Issue by SeanLatimer** [AMereBagatelle/fabricskyboxes#112]
Hey,

I'm curious if there's going to be a bugfix release for 1.20.1? There's a lot of packs still stuck on this version that a backport would be greatly appreciated.

Thanks

**Comment by AMereBagatelle** [comment]
Currently, all development effort is going to developing a large update for 1.20.6.  This doesn't rule out a bugfix release, but it is not actively on the radar.
