### ISSUE TITLE
Pls fix ur mod

### ISSUE THREAD

**Issue by clientwareoncw** [AMereBagatelle/fabricskyboxes#113]
![2024-05-18_09 19 51](https://github.com/AMereBagatelle/fabricskyboxes/assets/170166260/2d19574c-1b0d-4549-a839-9c7e4eab8b7a)

the mod is working but on the left top there is weird codes or smth how can i fix that?

**Comment by lowercasebtw** [comment]
go into keybinds, find FabricSkyboxes, check the keybind for Debug Screen, exit into game, and press the keybind, then unbind it

**Comment by clientwareoncw** [comment]
> go into keybinds, find FabricSkyboxes, check the keybind for Debug Screen, exit into game, and press the keybind, then unbind it

thx it worked

**Comment by lowercasebtw** [comment]
np
