### ISSUE TITLE
Enabling 2 specific resource packs causes crash in 1.21 fabric

### ISSUE THREAD

**Issue by LAIDAN22** [AMereBagatelle/fabricskyboxes#118]
**Bug Description:**

when enabling Dramatic skys 1.5.3.24 or Hyper Realistic Sky 2.1 and or loading in then enabling the resource packs, it will crash minecraft entirely. 

Though another resource pack works fine called "better sky". So im not sure if this is a conflict on the recourse pack developers end for the 2 in question or plausibly this mod being the foundation.

_All mods used are client sided and don't actively affect a vanilla server i play with friends on_

_edited: (I'll also add no shaders were enabled, just to ensure compatibility and checking for user end error while testing)_

**Pictures of Visual Error**

nothing loaded in menu:
![picture1](https://github.com/AMereBagatelle/fabricskyboxes/assets/173115036/6374b760-3f40-40c1-9f62-50da46fb3424)

Loaded in, no crash
![picture2](https://github.com/AMereBagatelle/fabricskyboxes/assets/173115036/d3ba84c5-26c9-437b-8dd5-9b11816cae6a)

enabling 1 of the 2 resource packs in question
![picture3](https://github.com/AMereBagatelle/fabricskyboxes/assets/173115036/6c695268-eaf6-44dc-8b83-be92cef6ac4b)

disaster
![picture4](https://github.com/AMereBagatelle/fabricskyboxes/assets/173115036/234c365f-f799-47e9-b25f-031bbc8253e8)

**System Details**
CPU: 32x AMD Ryzen 9 5950X 16-Core Processor
GPU: NVIDIA GeForce RTX 3070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 555.99)
OS: Windows 10 (10.0)

Minecraft Version: Fabric 1.21
Nuit Version: (unsure what nuit means)

Here is the modpack (i use modrinth so if you want to quickly run a test on your system here it is)

[1.21 davyjoneslocker 1.0.0.zip](https://github.com/user-attachments/files/15879754/1.21.davyjoneslocker.1.0.0.zip)

Crash Log:
https://mclo.gs/LeWW8tH

(edited for clarity in bug description)

**Comment by dopemike** [comment]
same here...

Time: 2024-06-21 01:49:30
Description: Unexpected error

java.lang.IllegalStateException: BufferBuilder was empty
	at net.minecraft.class_287.method_60800(class_287.java:69)
	at me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer.render(CloudRenderer.java:100)
	at net.minecraft.class_761.method_3259(class_761.java:17180)
	at net.minecraft.class_761.method_22710(class_761.java:1260)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_60800(class_287.java:69)
	at me.jellysquid.mods.sodium.client.render.immediate.CloudRenderer.render(CloudRenderer.java:100)
	at net.minecraft.class_761.method_3259(class_761.java:17180)
	at net.minecraft.class_761.method_22710(class_761.java:1260)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Uptime --
Details:
	JVM uptime: 157.113s
	Wall uptime: 131.960s
	High-res time: 128.365s
	Client ticks: 2403 ticks / 120.150s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['mikeyyy787'/48, l='ClientLevel', x=81.53, y=57.00, z=-20.28]]
	Chunk stats: 16384, 1021 F: 73 L: 0 U: 0 C: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,56,0), Section: (at 0,8,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 862192 game time, 38330 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 35

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: No
	Packs: vanilla, fabric, ambientsounds, animal_feeding_trough, autohud, balm-fabric, betterf3, betterstats, bobby, c2me, capes, cloth-config, creativecore, enhancedblockentities, entity_model_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fallingleaves, firstperson, forgeconfigapiport, indium, indypets, iris, isometric-renders, kiwi, libbamboo, lithium, mob_armor_trims, modmenu, neutral_animals, notenoughanimations, owo, persistent_parrots, realisticbees, reeses-sodium-options, sereneseasons, snowrealmagic, sodium, sound_physics_remastered, tcdcommons, timm, visuality, waystones, worldmesher, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, zoomify, file/MeineKraft 1.21.zip, file/MeineKraft 1.21 Custom.zip, file/MeineKraft 1.21 Mobs.zip, file/Hyper_Realistic_Sky_[v2.1].zip, file/See-Through Pumpkinhead.zip, file/Lost Nostalgia Music Pack Add-On.zip, file/Musik für die Seele

**Comment by FlashyReese** [comment]
This issue pertains to Sodium; their cloud renderer breaks when loading custom cloud textures from resource packs. Temporarily resolve this by removing the custom cloud textures. However, this problem cannot be fixed here and is unrelated to our project.
