### ISSUE TITLE
Skyboxes do not render if view distance is less than 4

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [AMereBagatelle/fabricskyboxes#12]
View distance 4:
![2021-02-20_17 13 30](https://user-images.githubusercontent.com/68545280/108603282-10931100-739f-11eb-8a1f-1717833043a4.png)

View distance 3:
![2021-02-20_17 13 39](https://user-images.githubusercontent.com/68545280/108603287-17ba1f00-739f-11eb-8823-8b0631e427f9.png)

**Comment by SnooComics9452** [comment]
it can't happened without sodium i think

**Comment by DragonEggBedrockBreaking** [comment]
> it can't happened without sodium i think

I can reproduce without sodium.

**Comment by Rajbir98** [comment]
This is now fixed in latest release but 2 render distance is working but a bit broken

**Comment by AMereBagatelle** [comment]
Closing as fixed, as the view-distance limiting code is no longer present in Minecraft 1.17.1.
