### ISSUE TITLE
Blindness potion does not affect skybox

### ISSUE THREAD

**Issue by heymanMC** [AMereBagatelle/fabricskyboxes#14]
See screenshot below. The skybox should not be visible when a player has the blindness effect.

![image](https://user-images.githubusercontent.com/38384673/114062021-465b5e80-9854-11eb-9956-f55ba5be8810.png)

**Comment by heymanMC** [comment]
Fix for this here: https://github.com/AMereBagatelle/fabricskyboxes/pull/15

**Comment by DragonEggBedrockBreaking** [comment]
fixed in d52175c8523a1dae2b25f3d7351dffd8305e530f
