### ISSUE TITLE
Nether fog does not replicate vanilla with a skybox enabled in the nether

### ISSUE THREAD

**Issue by AMereBagatelle** [AMereBagatelle/fabricskyboxes#16]
Nether skyboxes don't keep the same fog as the vanilla skybox.

With a skybox:
![With FSB](https://media.discordapp.net/attachments/756204001015496704/834951097797050388/2021-04-22_18.36.48.png?width=1192&height=670)

Without:
![Without FSB](https://media.discordapp.net/attachments/756204001015496704/834951318933209088/2021-04-22_18.38.06.png?width=1192&height=670)

**Comment by AMereBagatelle** [comment]
Cannot reproduce in 1.17.1 with FabricSkyboxes 0.5.2.  Unsure if issue still exists.

**Comment by austin-hobbs** [comment]
No longer exists due to disallowing nether skyboxes.

**Comment by AMereBagatelle** [comment]
Closing for now, due to being unsure if problem actually exists.
