### ISSUE TITLE
Textures completely scrambled when using MCPP, FSB 0.5.0, and Colormatic

### ISSUE THREAD

**Issue by i-like-trains72** [AMereBagatelle/fabricskyboxes#17]
I'll link to an issue on my github when I first saw this after using FSB 0.5.0, no idea how this happened. 
[https://github.com/i-like-trains72/optifine-resourcepack-conversion/issues/6](https://github.com/i-like-trains72/optifine-resourcepack-conversion/issues/6)

Screenshot from the issue: 
![image](https://user-images.githubusercontent.com/82773235/118220721-4994cc00-b44a-11eb-985b-dd746354abf8.png)

As you can see the textures are very very weird.
![2021-05-09_11 10 28](https://user-images.githubusercontent.com/82773235/118221038-db043e00-b44a-11eb-8f35-3473424c0581.png)

Breaking a block fixes any blocks that have the weird texture in the chunk you do it in. I have to do this for all the different blocks in a chunk. 
Any ideas...?

**Comment by supsm** [comment]
can't reproduce

**Comment by AMereBagatelle** [comment]
1. Are you sure that it's only when colormatic and FSB are both installed?
2. Can you provide logs?

**Comment by i-like-trains72** [comment]
I use MCPP as well because FSB does not change water or lighting, that's what MCPP's conversion to Colormatic's format is for

**Comment by AMereBagatelle** [comment]
Please reopen if there is more information that I can use to debug this.
