### ISSUE TITLE
Clouds not faded into blue sky like optifine

### ISSUE THREAD

**Issue by sharpenedblade** [AMereBagatelle/fabricskyboxes#19]

**Comment by Art1f4ct** [comment]
I've been messing around a bit and it seems as though whenever FSB is rendering something, it renders the fog layer as the entire skybox. Interestingly, this means that if you go below the world, where the fog color turns black, the entire sky turns black too. I believe that this is a likely explanation for why all the skyboxes that use add blending look washed out.
![2023-02-04_00 19 02](https://user-images.githubusercontent.com/73558637/216757023-1068f938-4b32-461f-a0f8-26cbf2bc7b80.png)
![2023-02-04_00 19 12](https://user-images.githubusercontent.com/73558637/216757026-0eb97f07-9544-451e-9e2e-2e88fc05f739.png)
![2023-02-04_00 19 39](https://user-images.githubusercontent.com/73558637/216757029-54e4ae38-46fd-4eac-a608-57865fedf9bf.png)
![2023-02-04_00 19 50](https://user-images.githubusercontent.com/73558637/216757030-c94fb218-dd34-443f-a561-9abd5d3e62c8.png)
![2023-02-04_00 20 42](https://user-images.githubusercontent.com/73558637/216757032-c4d4dc61-c48a-42fd-86d1-288d335d4d29.png)
![2023-02-04_00 20 53](https://user-images.githubusercontent.com/73558637/216757033-05911acb-2f8e-4ac6-acba-f897bedc7c31.png)

**Comment by Zekiu** [comment]
Any news on when this will get fixed? The difference between OptiFine and FabricSkyBoxes is quite jarring.
Optifine: 
![2023-05-07_16 33 34](https://user-images.githubusercontent.com/68301723/236690553-ccf53409-4ce6-41c0-bca7-bf1e478b59b5.png)
![2023-05-07_18 47 35](https://user-images.githubusercontent.com/68301723/236691106-697130f5-741f-4304-b374-71b720db969f.png)

FabricSkyBoxes: 
![2023-05-07_18 33 43](https://user-images.githubusercontent.com/68301723/236690594-b830833a-decc-4133-886e-ec8a8742f58d.png)
![2023-05-07_18 47 26](https://user-images.githubusercontent.com/68301723/236691112-c8f2dcd2-1b22-4ec4-972e-298da9cbde0f.png)

**Comment by UsernameGeri** [comment]
This is because- it turns out- FSB does not render the vanilla sky during sunset and sunrise (or at all, during the day either?) but instead renders its own sky. So the texture blending looks different. A `vanilla` sky type was already added, but it's not yet published.

**Comment by FlashyReese** [comment]
It's fixed in the development branch just be patient, it will be released sometime between now and the heat death of the universe. :)

**Comment by FlashyReese** [comment]
With the release of `0.7.0`, FSB has added `overworld` and `end` sky types. 

# For End Users
If you are a FabricSkyBoxes-Interop user update to `1.3.1` and conversions shall handle them automatically. If you are using MCPPPP, at the time of writing you will need to wait for the author to update and support it.


# For Resource Pack Creators
If you are a resource pack creator please add them.

Here is an example overworld sky that renders the sunrise/sunset effect.
```json
{
  "schemaVersion": 2,
  "type": "overworld",
  "properties": {
    "priority": -2147483648,
    "fade": {
      "alwaysOn": true
    }
  },
  "conditions": {
    "worlds": [
      "minecraft:overworld"
    ]
  }
}
```

Here is a decorations overlay if needed.
```json
{
  "schemaVersion": 2,
  "type": "monocolor",
  "blend": {
    "type": "replace"
  },
  "properties": {
    "priority": 2147483647,
    "fade": {
      "alwaysOn": true
    }
  },
  "decorations": {
    "showSun": true,
    "showMoon": true,
    "showStars": true
  },
  "conditions": {
    "worlds": [
      "minecraft:overworld"
    ]
  }
}
```
