### ISSUE TITLE
Sky Textures Pop In/Out When Switching Biomes

### ISSUE THREAD

**Issue by Deadmano** [AMereBagatelle/fabricskyboxes#22]
The fade in/out works perfectly if stationary in a single biome based off of the time of day, however if you have a setup that involves various sky textures for different biomes it introduces a jarring pop in and out effect each time you cross into a new biome. Is there a way to address this that does not involve editing tons of configuration files for each new sky instance?

**Comment by AMereBagatelle** [comment]
Have you tried the transition speed variable in the default properties object? https://github.com/AMereBagatelle/fabricskyboxes/blob/1.17.x-dev/docs/schema-v2.md#default-properties-object
There is no way to fix it without editing each configuration file.

**Comment by AMereBagatelle** [comment]
Closing, for desired effect transition speed should be <0.1 to more slowly fade in/out.
