### ISSUE TITLE
Upload mod to Curseforge

### ISSUE THREAD

**Issue by Pectacular** [AMereBagatelle/fabricskyboxes#27]

**Comment by supsm** [comment]
It's on [modrinth](https://modrinth.com/mod/fabricskyboxes), and there is a very obvious message that tells you to download it there instead.

**Comment by Pectacular** [comment]
I use the Curseforge launcher, so I cannot install this mod from Modrinth. That is why I am asking the author to upload the mod to Curseforge

**Comment by AMereBagatelle** [comment]
I would be open to again using CurseForge, however my largest problem with it is that every way of automating it seems to result in problems (corruption, hashes, etc).  I would like to (just like I can now) just make a github release and everything will be automated.

All that said, I'll consider it.

**Comment by RaptaG** [comment]
Also, it would be very useful for modpacks and modpack developers (eg. https://github.com/Fabulously-Optimized/fabulously-optimized and https://github.com/Fabulously-Optimized/fabulously-optimized/issues/72)
