### ISSUE TITLE
Optifine format support

### ISSUE THREAD

**Issue by ghost** [AMereBagatelle/fabricskyboxes#29]
Will Optifine support ever be implemented?
It is not convenient to convert each resource pack

**Comment by JustCat80** [comment]
> Disclaimer: Does not support Optifine skybox resource packs. This is not planned.

This is in the readme, so probably not atm

**Comment by AMereBagatelle** [comment]
I do not plan on supporting them.  My ideal dream is that I can call something like MCPPPP as a API in the mod in order to convert packs, but native support for the format is not planned.
