### ISSUE TITLE
Underwater Fog is broken

### ISSUE THREAD

**Issue by Marcelo20XX** [AMereBagatelle/fabricskyboxes#31]
The Skybox is visible instead of being clouded by the underwater fog, tested the issue on Java Edtition 1.17.1 and 1.18.1

**Comment by AMereBagatelle** [comment]
Can reproduce, the bug seems to be fixed by Sodium somehow.  Not sure why yet, but it works as a temporary fix to this issue.

**Comment by Marcelo20XX** [comment]
which version of sodium fixes the issue?

**Comment by AMereBagatelle** [comment]
This is now confirmed to be vanilla behavior, simply rearing its head in an ugly way.  #45 fixes this, however the verdict of whether the behavior will be kept is still unclear.

**Comment by FlashyReese** [comment]
Should be resolve in https://github.com/AMereBagatelle/fabricskyboxes/commit/ea4724e3984501d940a0eade82335f9d15b49c90, this will be available in the next release.
