### ISSUE TITLE
Licensed mods are on the mod release site in China

### ISSUE THREAD

**Issue by MoMoOfficiaL** [AMereBagatelle/fabricskyboxes#36]
What do you know in the title

**Comment by AMereBagatelle** [comment]
Not even sure what that means, therefore... no I guess?  Without further explanation I have no clue what a "module encyclopedia" is and Google is giving me nothing useful.

**Comment by MoMoOfficiaL** [comment]
Sorry I didn't say specificall
![捕获](https://user-images.githubusercontent.com/85117283/180627461-8a936c9d-d5ba-4a11-93b2-9b454294ad74.PNG)
y

**Comment by AMereBagatelle** [comment]
I'm still going to deny unless there is a specific reason I should that is well-explained.  I have no clue why this website exists, what it actually does, or anything about it, and as such am extremely hesitant to give it permission to redistribute my mod files.

**Comment by MoMoOfficiaL** [comment]
**Minecraft Encyclopedia** (mcmod.cn) is a **non-profit knowledge sharing platform.**
Your mod release Website link "**https://www.mcmod.cn/class/5950.html**" This is basically a mod release website
The website has a strict audit system

**Comment by MoMoOfficiaL** [comment]
Also thank you for making this mod

**Comment by AMereBagatelle** [comment]
I don't want random websites that I don't and can't keep track of redistributing my mods.  The downloads on Modrinth, Github, or Curseforge should work just fine.

**Comment by MoMoOfficiaL** [comment]
OK I got it
