### ISSUE TITLE
Sun becomes dimmer after one day cycle

### ISSUE THREAD

**Issue by cafuneandchill** [AMereBagatelle/fabricskyboxes#37]
**Bug description:** Sun becomes less visible after the second sunrise. At the first day, it is fully visible. Reloading the pack via `F3 + T` resolves the issue, but for one day cycle only.

**Minecraft version:** 1.18.2

**FSB version:** 0.5.5

## Steps to reproduce

1. Use this resource pack: [fsb_test.zip](https://github.com/AMereBagatelle/fabricskyboxes/files/8463859/fsb_test.zip)
2. Wait until the next in-game sunrise or do it via commands:

    ```mcfunction
    time set day
    time set night
    time set day
    ```

**Comment by AMereBagatelle** [comment]
I can reproduce this issue with 0.5.6, however the sun disappears entirely instead of simply dimming.  I believe this is because of a separate but related bug affecting the sun's transition from one skybox to another during sunset/sunrise.

**Comment by AMereBagatelle** [comment]
Cannot reproduce after the newest changes to 1.19.x-dev.  Please reopen if this issue is still occurring.
