### ISSUE TITLE
Game Crashes after installing pack that needs to be converted 

### ISSUE THREAD

**Issue by RaptaG** [AMereBagatelle/fabricskyboxes#39]
[Crashlog](https://0x0.st/ocEq.txt)
Using latest FSB and MCPPPP

**Comment by Madis0** [comment]
@RaptaG I think you should convert the pack with [the standalone converter](https://github.com/supsm/MCPPPP/releases) (instead of the mod) and then check if the converted pack works with this mod.

**Comment by RaptaG** [comment]
> @RaptaG I think you should convert the pack with the standalone converter (instead of the mod) and then check if the converted pack works with this mod.

Yep, that was it -_-
