### ISSUE TITLE
1.19 doesn't  work with my pack, but 1.18 does

### ISSUE THREAD

**Issue by litoj** [AMereBagatelle/fabricskyboxes#46]
I have a resourcepack where I tried to port the DrammaticSkies resourcepack, but on the new version it doesn't work.
What could have caused this?
PS: [pack](https://github.com/JosefLitos/Enhanced-Faithcraft/tree/master/assets/fabricskyboxes/sky)

**Comment by SunnySlopes** [comment]
I share the same problem with you

**Comment by AMereBagatelle** [comment]
Please post an error or other debugging information if you are still having this problem with the latest version.

**Comment by litoj** [comment]
Works like a charm, thank you.
