### ISSUE TITLE
1.19 flaky behavior

### ISSUE THREAD

**Issue by alex-huff** [AMereBagatelle/fabricskyboxes#48]
https://youtu.be/EmeSBsigZyI
I am experiencing weird behavior with the 1.19 version of this mod.
On the left is 1.18.1 with fabricskyboxes 0.5.4
On the right is 1.19 with fabricskyboxes 0.5.6
Both clients only have the fabric-api and fabricskyboxes installed.

**Comment by alex-huff** [comment]
#44 seems to fix this.

**Comment by MoMoOfficiaL** [comment]
Good me too

**Comment by MoMoOfficiaL** [comment]
me too

**Comment by alex-huff** [comment]
> #44 seems to fix this.

Been running #44 for a week and the problem is completely gone.
