### ISSUE TITLE
No skybox textures, only white skies

### ISSUE THREAD

**Issue by XDCam15** [AMereBagatelle/fabricskyboxes#50]
Since optifabric wouldn't work with a certain mod I'm using, I had to resort to this mod to use custom skyboxes. It seemed promising, however it is being very inconsistent. The textures will not show up and instead there is a white sky everywhere I look, and I was only able to get the textures to show up one time for a brief moment and idk how I made that happen. 

Idk if I'm using out of date resource packs or what, but this issue needs to be fixed since it's basically broken on my end.

**Comment by moehreag** [comment]
This is probably being fixed by #44
