### ISSUE TITLE
Sun "pops" into and out of existence during sunrise/sunset transition

### ISSUE THREAD

**Issue by AMereBagatelle** [AMereBagatelle/fabricskyboxes#54]
Reproduction steps:
- Install a resource pack with a transition at sunrise/sunset
- /time set 23500
- Observe

**Comment by SyndiShanX** [comment]
Any eta on a fix for this?

**Comment by ShadowFlandre** [comment]
^

**Comment by FlashyReese** [comment]
This should be fixed with the latest release.
