### ISSUE TITLE
The weather option is broken.

### ISSUE THREAD

**Issue by KeWHs** [AMereBagatelle/fabricskyboxes#56]
i make a skybox that only render in clear weather. but it's still rendered in rainy day (changed by command)
i also use sodium and iris, and im sure its not iris's issue.
![image](https://user-images.githubusercontent.com/71676400/182276466-1c663edb-c8e4-4364-bea6-63065826328c.png)

**Comment by KeWHs** [comment]
and the skybox pop in/out when change weather. i've used transition speed variable but it doesn't work.

**Comment by m-valkov** [comment]
@Dantigator 
I would like a little more information.
What is the version of minecraft, fabric and fabricskyboxes.
It would also be nice to have a link to the resourcespack with which the problem.

**Comment by FlashyReese** [comment]
Resolved in https://github.com/AMereBagatelle/fabricskyboxes/commit/6db5749cf276ab82324392d5de2fc624ed63ed8c
