### ISSUE TITLE
CurseForge version 1.18.2

### ISSUE THREAD

**Issue by Disguys** [AMereBagatelle/fabricskyboxes#58]
Hi, I know that there is a version 1.18.2 on modrinth, but could you upload the version for 1.18.2 on CurseForge, I just need it for a ModPack, please.

**Comment by RaptaG** [comment]
See, `mc-publish` does not upload older mod versions and I think @AMereBagatelle won’t publish that version manually either. Distribute your modpack in Modrinth is also a solution too, Modrinth is great! (P.S. It’s not ModPack, it’s Modpack..)

**Comment by AMereBagatelle** [comment]
Correct.  I do not plan to publish older and unsupported versions on CurseForge.
