### ISSUE TITLE
Sun/Moon doesn't appear

### ISSUE THREAD

**Issue by AyJ4yTee** [AMereBagatelle/fabricskyboxes#63]
The sun/moon is supposed to be right above my head since it's noon, yet only the glow from it appears. The sun texture itself doesn't. How do I fix this?

![2022-08-26_15 20 41](https://user-images.githubusercontent.com/111235222/186913130-c5c82614-9b1a-4666-9a6a-706870534cd4.png)
![2022-08-26_15 20 46](https://user-images.githubusercontent.com/111235222/186913150-532745fd-c561-4dde-b10c-b480d28390c3.png)

**Comment by m-valkov** [comment]
If it's hyper realistic, and it looks that way, it's a crooked resource pack. The author has made the configs as if they were. That's why it doesn't work.

**Comment by FlashyReese** [comment]
This should no longer be an issue and has been resolved.
