### ISSUE TITLE
[1.18.2]it is not work on sever

### ISSUE THREAD

**Issue by WolfGenerals** [AMereBagatelle/fabricskyboxes#64]
it works well in my world but not on server
I guess it because the world's name is bskyblock_world
![Screenshot_20220924_103005_com mio launcher](https://user-images.githubusercontent.com/97285357/192076622-c4071144-fe27-49c4-9c53-9322eafd973d.jpg)
![Screenshot_20220924_102414_com mio launcher](https://user-images.githubusercontent.com/97285357/192076668-780e042e-4ed9-4592-a3ba-42734762c513.jpg)

**Comment by m-valkov** [comment]
I think it's time to do a release with my fixes

**Comment by WolfGenerals** [comment]
I'll wait for it

**Comment by FlashyReese** [comment]
Does this still occur in the release of `0.6.0`?
