### ISSUE TITLE
Top skybox face appears to be rotated 90 degrees clockwise

### ISSUE THREAD

**Issue by alex-huff** [AMereBagatelle/fabricskyboxes#73]
[Example](https://i.imgur.com/weQ0cNG.jpeg)
I get this issue in 1.19.2 and 1.19.3. I verified that it is present with only fabricskyboxes and fabric API installed. This screenshot was taken with FSB version 0.6.1.

**Comment by alex-huff** [comment]
Reverting the changes to [SquaredTexturedSkybox.java](https://github.com/AMereBagatelle/fabricskyboxes/blob/1.19.x-dev/src/main/java/io/github/amerebagatelle/fabricskyboxes/skyboxes/textured/SquareTexturedSkybox.java) from [e76f803](https://github.com/AMereBagatelle/fabricskyboxes/commit/e76f8030e303485f2554bb1248eb610537c8e62a) fixed this issue for me. I don't know what the original intent of that change was, or if it was a mistake, but it appears to have caused my problem.

**Comment by moehreag** [comment]
well, the commit message says that it fixed it to be within the spec, rather than outside it (as it was before). This needs to be fixed in your resource pack that provides the sky.

**Comment by alex-huff** [comment]
Yeah, [it was fixed](https://github.com/heymanMC/Awesome-Skies/commit/7e884ee76e5a7cbe45d79295957bd5b74ee9659e). I don't know why I didn't just read the commit message.
