### ISSUE TITLE
[0.6.4 & 0.6.5] Rotation isn't smooth on certain modded servers

### ISSUE THREAD

**Issue by pkfortis** [AMereBagatelle/fabricskyboxes#83]
No matter what I set the rotation speed of the starfield to, the animation refuses to run smoothly when connected to my PaperMC server. In singleplayer and when connected to a vanilla server, the animation plays as expected.

Here's a video of the jerky animation. The stars should be moving at about the same speed as the moon normally would be, and sort of are, but... yeah:
https://www.youtube.com/watch?v=Zd1_qQ9gpp0

**Comment by Vaskyy** [comment]
1.19.3
Have the same Issue on a Fabric MP Server.
SP is completly fine.
https://www.youtube.com/watch?v=H5chwllbCpQ

**Comment by pkfortis** [comment]
I did a little more testing. I can confirm that this issue occurs with both versions 0.6.4 and 0.6.5 on 1.19.4.

**Comment by Vaskyy** [comment]
most things got changed in 0.6.3.
so i guess after this version the problems occur.

**Comment by supsm** [comment]
@Vaskyy What mods are on the server?

**Comment by Vaskyy** [comment]
• No Enderman griefing
• More mob heads
• Player heads drop
• XP Clumps
• Starlight
• Sodium
• No Chat Reporting
• ItemSwapper

**Comment by supsm** [comment]
Sodium on the server? Did you mean lithium? If so, which version is being used?

**Comment by Vaskyy** [comment]
yes i meant lithium
lithium-fabric-mc1.19.3-0.10.4
