### ISSUE TITLE
FSB Quilt Support

### ISSUE THREAD

**Issue by Rgiulini99** [AMereBagatelle/fabricskyboxes#88]
# Hello
###  The Quilted Fabric API Can Be Too Incompatible
**Pls @AMerebagatelle Make A Quilt Version**
_This Is A Request (Add The Enhancement Label)_

**Comment by FlashyReese** [comment]
![2023-06-01_09 57 37](https://github.com/AMereBagatelle/fabricskyboxes/assets/30311066/233ef42c-ce2c-4a4e-beb2-88cc2984456f)

I don't see what's the issue you are having, as you can see on the screenshot above it's compatible with Quilt.

**Comment by Rgiulini99** [comment]
But Is the QSL

**Comment by Rgiulini99** [comment]
# Ok Thanks
