### ISSUE TITLE
I can see all mobs when being underwater

### ISSUE THREAD

**Issue by icynstant** [AMereBagatelle/fabricskyboxes#93]
I also see mobs on ground behind trees or hills, for me it feels illegal

With mod and RP Dramatic Skys:
![2023-07-16_12 25 21](https://github.com/AMereBagatelle/fabricskyboxes/assets/127024748/c5d21b01-c60d-4b10-834d-ba4a0bb5ef34)

FabricSkyBoxes disabled:
![2023-07-16_12 25 24](https://github.com/AMereBagatelle/fabricskyboxes/assets/127024748/237c9ef6-b2f9-45b2-96e6-6f6797c8986e)

I think someone mentioned this problem but i haven't found issue like mine

**Comment by UsernameGeri** [comment]
Yeah it's a known issue. https://discord.com/channels/756203400089305128/756203400592621571/1112650767803883600
#89 is probably related

**Comment by FlashyReese** [comment]
It's actually related to https://github.com/AMereBagatelle/fabricskyboxes/issues/31#issuecomment-1193192513. 

To quickly explain vanilla's overworld skybox isn't really a skybox the only time it stops rendering the sky is when in lava/powder snow, player having blindness or darkness and in thick fog(nether).

**Comment by FlashyReese** [comment]
Closing this issue, this has been resolved with a commit that will in the next release. More information can be found in #31.
