### ISSUE TITLE
fog colour on surrounding chunks doesnt match

### ISSUE THREAD

**Issue by Moonyol** [AMereBagatelle/fabricskyboxes#99]
off: ![image](https://github.com/AMereBagatelle/fabricskyboxes/assets/92951072/b83b0ff9-35c1-42d2-acda-9334e9693ba1)
on: ![image](https://github.com/AMereBagatelle/fabricskyboxes/assets/92951072/a8abd0ec-66f3-49cb-8087-fb0fca09488f)
(dramatic skies demo 1.5.3.4)

**Comment by UsernameGeri** [comment]
This is normal.

You can change the fog colors to match the sky as best you can.
https://github.com/AMereBagatelle/fabricskyboxes/blob/1.20.x/dev/docs/schema-v2.md#properties-object
